Added UnknownWidget
When a widget class has been deleted, `prefetch_tree` is no longer able
to find the classes for content types and ends up raising
`AttributeError: 'NoneType' object has no attribute 'objects'`.
@gavinwahl proposed returning a noop content type that is not draggable,
editable, and renders to an empty string.